stages: 
  - build
  - deploy
  - showlog
build: 
  stage: build
  variables: 
    GIT_STRATEGY: clone
  script: 
    - npm ci
    - npm run build
  tags: 
    - dev-server
deploy: 
  stage: deploy
  variables: 
    GIT_STRATEGY: none
  script: 
    - sudo cp -rf dist/ /data/bookshop/
    - sudo cp -rf node_modules/ /data/bookshop/
    - sudo chown -R bookshop /data/bookshop
    - sudo su bookshop -c "kill -9 $(ps -ef | grep  dist/main.js | grep -v grep | awk '{print $2}')"
    - sudo su bookshop -c "cd /data/bookshop; nohup node dist/main.js > log.out 2>&1 &"
  tags: 
    - dev-server
showlog: 
    stage: showlog
    script: 
      - sudo su bookshop -c "tail -n 100 /data/bookshop/log.out"
    tags: 
      - dev-server
